### ISSUE TITLE
Feature Request: Change message visibility timeout

### ISSUE THREAD

**Issue by PizzaBrandon** [TechnologyAdvice/Squiss#11]
It may sometimes be desirable to put a message back on the queue right away to be picked up again, rather than just "keeping" it and letting the default queue visibility timeout occur. This way one can maintain long visibility timeouts to allow for processing retries, but also be able to effectively use the dead letter queue.

http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/SQS.html#changeMessageVisibility-property

Requesting two API additions:

`squiss.changeMessageVisibility(message|receiptHandle, seconds)`

and

`message.changeVisibility(seconds)`

These can be used in conjunction with `message.keep` if you want to return the message to the queue and free up an inFlight space, or to extend the message timeout if processing is taking a long time.

I'll see if I can free up some time to do the above as a PR if you want this as a contribution.

**Comment by tothandras** [comment]
@PizzaBrandon see #16.

**Comment by TomFrost** [comment]
Closing as addressed, will be released in a new minor version shortly.
