### ISSUE TITLE
Feature request: support deletion of previously handled messages

### ISSUE THREAD

**Issue by mlilley** [TechnologyAdvice/Squiss#12]
In my scenario, "processing" a message involves delivering it to some other system component, and then calling .handledMessage() so I can continue to process further messages.  When this other component responds that it's done, I want to call .deleteMessage().  This arrangement allows me to leverage visibility timeouts to implement a kind of timeout/retry mechanism, without moving the message between additional queues.

This doesn't quite fit Squiss' intended usage pattern, and the handledMessage() followed by a subsequent deleteMessage() results in a double decrementing of the number of inflight messages.

Would you be amenable to having a variant of deleteMessage() that does it's thing, but not decrement the messages inflight?

**Comment by TomFrost** [comment]
Hmm, I'm not sure I like the mechanics of this. The idea behind the maximum in-flight cap is that that's the total number of messages your app can handle at one time. If you're looking to accept another message _over_ that cap, the solution isn't to trick Squiss into thinking a message has been handled before it's truly handled, it would be to increase the in-flight cap.

**Comment by mlilley** [comment]
Totally fair enough. I understand the mechanics of the in-flight limit used here, and think you've captured the common mode just fine.

My use case had me wanting to separate the act of handling a message from deleting it.  It was a bit of an ugly design and probably not a common thing for squiss' users to do.
